#! /bin/sh

sxhkd &
unclutter &
compton -f &
feh --bg-scale ~/.cache/wal/wal/ &
wal -R --vte &
nm-applet &
xrdb ~/.Xresources &
dunst &
xmodmap -e "clear lock" &
xmodmap -e "keysym Caps_Lock = Escape" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &
