#!/bin/mksh

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 119.99 --rotate normal\
    --output DP-0 --mode 1920x1080 --rate 120 --rotate normal --right-of HDMI-0\
    --output DP-2 --mode 1920x1080 --rate 120 --rotate normal --left-of HDMI-0;

sxhkd &
unclutter &
picom -f &
feh --bg-scale ~/.config/desktop/background.jpg &
xrdb ~/.Xresources &
dunst &
nm-applet &
blueman-applet &
polychromatic-tray-applet &
bash ~/.config/polybar/launch.sh 
bash ~/work/start_headless_vms

bspc monitor HDMI-0 -d I II III
bspc monitor DP-0 -d IV V
bspc monitor DP-2 -d VI VII

bspc config automatic_scheme alternate 
bspc config initial_polarity second_child
bspc config border_width         0 
bspc config window_gap           10
bspc config split_ratio          0.64
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#48a5CF" 
bspc config ignore_ewmh_fullscreen enter
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_side

bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Yad state=floating
bspc rule -a yad-calendar state=floating
