#!/bin/mksh

sxhkd &
unclutter &
#picom -f &
feh --bg-scale ~/.config/desktop/background.jpg &
xrdb ~/.Xresources &
dunst &
polybar topbar &
polychromatic-tray-applet &
connman-gtk &

bspc monitor DP-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X

bspc config automatic_scheme alternate 
bspc config initial_polarity second_child

bspc config border_width         0 
bspc config window_gap           10
bspc config split_ratio          0.64
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config presel_feedback_color "#48a5CF" 

bspc config ignore_ewmh_fullscreen enter

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
