#!/bin/bash
# Run Wine as user wine.
# Should only be used for running Windows software.

echo "Adding wine to X server permissions list."
xhost +SI:localuser:wine

echo "Running as wine:" "$@"
# Use sudo -u wine to run command (and all arguments) as user wine.
# and use env command to set environment variables for wine user.
sudo -u wine env HOME=/home/wine USER=wine USERNAME=wine LOGNAME=wine wine "$@"
