#!/bin/mksh
export LANG=en_US.utf8
export GOPATH=$HOME/go
export PATH=/usr/local/go/bin:$GOPATH/bin:$HOME/bin:$HOME/.local/bin:/sbin:/usr/sbin:$PATH
export MANPATH=$MANPATH:/usr/local/share/man
export MANPAGER="/bin/sh -c \"col -b | vim --noplugin -c 'set ft=man ts=8 nomod nolist nonu noma cc=' -\""
export ERL_AFLAGS="+pc unicode -kernel shell_history enabled"
export WINEARCH=win32
export WINEDEBUG=-all
export TERM=xterm-256color
export EDITOR=vim
export HISTFILE=$HOME/.mksh_history
export HISTSIZE=10000
export LESSSECURE=1

PS1='#'                   # Root
(( USER_ID )) && PS1='$'  # Regular user
PS1=$'\001\r''${|
    # Store exit code for later
    \typeset e=$?
    \typeset d=${PWD:-?}/
    \typeset p=~
    # Replace $HOME with ~
    [[ $p = ?(*/) ]] || d=${d/#$p\//\~/}
    d=${d%/}
    \typeset m=${%d} n p=…
    (( m > 0 )) || m=${#d}
    (( m > (n = (COLUMNS/3 < 7 ? 7 : COLUMNS/3)) )) && d=${d:(-n)} || p=
    REPLY+="[$p$d]"
    # Add exit code
    (( e )) && REPLY+=" $e "
    \return $e
}'"$PS1 "

echo -ne '\033%G'

# enable vi mode
set -o vi

# job control fully enabled
set -o monitor

# switch console to utf8 mode
set -o utf8-mode

case "$-" in *i*)
    alias k='cd ~/work'
    alias e='exit'
    alias c='clear'
    alias a='cd ~/vault'
    alias d='cd ~/dotfiles'
    alias q='cd ~'
    alias v='vim'
    alias l='ls --color'
    alias ls='ls --color'
    alias t='tmux -2 attach -t shell || tmux -2 new -s shell'
    alias jc='jupyter-console'
    alias jn='cd ~/Documents/notebooks && jupyter notebook&'
    alias gg='git status'
    alias python='python3'
    alias pip='pip3'
    ;;
esac

# Import colorscheme from 'wal'
(cat ~/.cache/wal/sequences &) >/dev/null 2>&1

# activate torch7
. /opt/torch/install/bin/torch-activate
